const Router = require('koa-router')
let musicRouter = new Router()
const musicControllers = require('../controllers/music')
musicRouter.get('/music/index',musicControllers.showIndex)
.get('/music/add-music',musicControllers.showAddMusic)
.get('/music/edit-music',musicControllers.showEdit)
.post('/music/add-music',musicControllers.addMusic)
.post('/music/update-music',musicControllers.updateMusic)
.get('/music/del-music',musicControllers.deleteMusic)
module.exports = musicRouter